### ISSUE TITLE
VPC template validation error

### ISSUE THREAD

**Issue by lbailly** [bonusbits/cloudformation_templates#6]
Hello,

When I try to instantiate the stack: https://s3.amazonaws.com/bonusbits-public/cloudformation-templates/github/vpc.yml using the create stack button, I got this error: Template validation error: Parameter 'VPCSubnetCidrBlock' must match pattern (\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})

Ludovic

**Comment by konchif** [comment]
Hi Ludovic,
please, try to replace with : '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
worked for me
Ari

**Comment by LevonBecker** [comment]
Welcome to fork, update and submit a pull request with the fix. It worked for me the last time I tried. Not sure what changed.
