### ISSUE TITLE
Requirement is - Highly available configuration of ArcGIS Portal, Server, and DataStore (Windows).

### ISSUE THREAD

**Issue by anonymouse-lab** [bonusbits/cloudformation_templates#7]
## Request : Requirement is - Highly available configuration of ArcGIS Portal, Server, and DataStore (Windows).
- [ ] Bug
- [ ] New Feature
- [ ] Refactor
- [X ] Question 
- [ ] Documentation
- [ X] Tests  
- [ ] Other

## Details
* ...

**I was going though some of the documents there is a AWS templet closely matching to the requirement   .... will any of you have some time to look in to it?  Please share suggestions you might have. I am not able to run it** 

Requirement is - Highly available configuration of ArcGIS Portal, Server, and DataStore (Windows).
![image]

(https://user-images.githubusercontent.com/30665725/36354522-df1806c6-14fb-11e8-8453-053820df71db.png)

Code : [Text.txt](https://github.com/bonusbits/cloudformation_templates/files/1734903/Text.txt)

**Comment by LevonBecker** [comment]
Everyone is welcome to fork, refactor/feature add and submit a pull request to share back with the community.
