### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish which is my native language. could translate any text provided it is a thousand words or more

### ISSUE THREAD

**Issue by LuigiBaute** [bonusbits/cloudformation_templates#8]
## Request
- [x] Bug
- [x] New Feature
- [x] Refactor
- [x] Question
- [x] Documentation
- [x] Tests
- [x] Other

## Details
* ...

**Comment by anonymouse-lab** [comment]
Requirement is - Highly available configuration of ArcGIS Portal, Server, and DataStore (Windows).
Can any of the developers help me out?

**Comment by LuigiBaute** [comment]
@sourav1985 Hi I can't help you with that, what I offered was a translation into any document to Spanish, if you guys are interested let me know to start right away, cheers!

**Comment by anonymouse-lab** [comment]
its would be fine. Is there any charge for it?

**Comment by LuigiBaute** [comment]
There is no charge for translations, if you tell me I start to translate now

**Comment by anonymouse-lab** [comment]
Yes, that would be helpfull.

**Comment by LevonBecker** [comment]
Sorry for the delayed response. Work keeps me busy. You are welcome help out. Just fork, refactor and submit a pull request with the changes (translations).
