### ISSUE TITLE
Chef

### ISSUE THREAD

**Issue by konchif** [bonusbits/cloudformation_templates#9]
## Request
- [V] Bug
- [ ] New Feature
- [ ] Refactor
- [V ] Question
- [ ] Documentation
- [ ] Tests
- [ ] Other

## Details
* Hi, I`ve tried to run Chef lab and it failed to create an instance with the following error:

CREATE_FAILED | AWS::EC2::Instance | EC2Instance | In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit http://aws.amazon.com/marketplace/pp?sku=8a3w64phkkutljzrbdqjrmc8f
-- | -- | -- | --
Please, advise,
Thanks,
Ari

**Comment by LevonBecker** [comment]
Sorry, I never got around to finishing that lab creation. You are welcome to fork, fix and submit a pull request with the refactor to share with others. I currently don't have the bandwidth to work on this.
